### ISSUE TITLE
The props attribute of the countryCodeSelect template broken in 1.2

### ISSUE THREAD

**Issue by JesperWe** [3stack-software/meteor-country-code-list-iso3166#1]
I tried this package in Meteor 1.2, but I get
```
    Exception in defer callback: Error: Failed to execute 'setAttribute' on 'Element': 'class="form-control"' is not a valid attribute name.
```

**Comment by nathan-muir** [comment]
Hi @JesperWe 

Can you provide a sample on how you're setting `props`? 

I'm using this package on Meteor 1.2 without any problems.

**Comment by JesperWe** [comment]
Well there is no documentation on how to do it so I experimented a bit.
But as I can see from the source you are just putting {{props}} into the <select>, so I tried props='class="form-control"' which is what is needed for bootstrap.

**Comment by nathan-muir** [comment]
Ok! With blaze, you must specify props as an object, so try:

```js
props = {"class": "form-control"}
```

**Comment by JesperWe** [comment]
Suggest to put that in your readme.
